### ISSUE TITLE
clashes with linters that lint on-save

### ISSUE THREAD

**Issue by michaelaye** [markbaas/atom-python-autopep8#1]
Could you help with this issue:
https://github.com/AtomLinter/linter-flake8/issues/64#issuecomment-130425317

Problem is that the linter-flake8 checks just before autopep8 changes the buffer, so I always have to save twice like this to avoid having errors that autopep8 already did repair.

Somehow, autopep8 should be running before the linter get's active, and the author of linter-flake8 recommend the setting `modifiesBuffer:true` for your plugin? But apparently, this is only supported by linter-plugins? Not sure about that, would be great if this could work together better.

**Comment by Arcanemagus** [comment]
As stated over there, this package would need to be re-written as a `linter` plugin to integrate like you are asking. `modifiesBuffer:true` only applies to `linter` plugins and has no bearing in this package.

**Comment by michaelaye** [comment]
ok, then i will resort to manual saving for now. Thanks!
