### ISSUE TITLE
executable not being picked up from PATH

### ISSUE THREAD

**Issue by michaelaye** [markbaas/atom-python-autopep8#2]
This seems to be a common problem currently in Atom, apparently some API has changed inside Atom that prevents this from working?
I currently have to provide the full path in the settings, as for flake8 and isort, those packages suffer from the same problem. I don't know if this should be solved on Atom level or on package level.
I would prefer the flexibility to have it set by the PATH environment because that way the currently active virtual environment decides which executable is being used for this. Even so maybe for pep8 there are no differences between Python2 and Python3?

**Comment by Sapphire64** [comment]
@michaelaye do you still have this problem? I just installed `autopep8` to my Mac and without restarting and anything else got `atom-python-autopep8` working, `Autopep8 Path` in settings is the default value.

**Comment by michaelaye** [comment]
currently i have the problem that it doesn't work at all, neither with the path set nor without. :(

**Comment by dpo** [comment]
Same here.

**Comment by harryjubb** [comment]
+1 here as well.

I get this in the status bar:

<img width="79" alt="run_parse_fpocket_py_ __users_hj4_google_drive_scripts" src="https://cloud.githubusercontent.com/assets/4588417/13557957/33773442-e3f0-11e5-8e4d-6d9c211abc68.png">

**Comment by Moini** [comment]
Same for me.

**Comment by tianjiqx** [comment]
me, too.I don't know  how to set the path.

**Comment by michaelaye** [comment]
Still not working here at all, neither with or without setting the path.
Atom: 1.14.4
macOS 10.11.6

**Comment by michaelaye** [comment]
I just implemented #5 in my fork, and all works, even without setting the path. Try my fork if you want. (apm install git-url works just fine) ;)  
https://github.com/michaelaye/atom-python-autopep8
