### ISSUE TITLE
Cannot make it work

### ISSUE THREAD

**Issue by michaelaye** [markbaas/atom-python-autopep8#6]
Atom: 1.12
OS: macOS 10.11.6
Python: 3.5 inside conda env

I use conda so to make sure `autopep8` is found, I put the absolute path to the executable into the settings.
I tried it both with the "Format on Save" option and the manual call via the menu, to no avail.
I have several PEP8 issues, like E225 (missing whitespace after operator).
When using `autopep8` inside the Terminal these issues are being found and corrected.
How can I help to debug this?

**Comment by kosmiciatakuja** [comment]
Same here, on Linux:
Atom 1.11.2
OS: Arch Linux
Python 3.5 in virtualenv with autopep8 installed.

**Comment by michaelaye** [comment]
It's most probably #5 , because I'm a magicpython user. @kosmiciatakuja are you?

**Comment by kosmiciatakuja** [comment]
@michaelaye no, sorry, I'm not

**Comment by michaelaye** [comment]
Well, I just implemented #5 myself and boom, it works.

**Comment by potens1** [comment]
Same here, magicpython user

**Comment by michaelaye** [comment]
Get my fork or edit these small changes yourself, it's easy. Look at #5 what needs to be changed.
